### ISSUE TITLE
Developer link is broken ;)

### ISSUE THREAD

**Issue by andig** [patharanordev/donate-in-git#2]

**Comment by patharanordev** [comment]
Oh, thank you @andig for inform me.

They are not support my country(Thailand) for now (>,<), I'm so sad. I got message below in `PayPal` page :
> Donations aren't supported in this organization's country

I still open the issue until got some solution from `PayPal` community.

Ref.
https://www.paypal-community.com/t5/Merchant-Products-and-Services/Donations-aren-t-supported-in-this-organization-s-country/m-p/2340985#

**Comment by patharanordev** [comment]
Using other donate platform to sync back to `PayPal` instead.
Ref. c1a559884497e6c2fe1528d5c2fac62964192ebb
